logging:
  level:
    com:
      ziuch:
        blog:
          api:
            mapper: trace
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
server:
  port: 9000
spring:
  application:
    name: blog-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ???????????
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: ???????
  devtools:
    livereload:
      port: 35739
  jackson:
    generator:
      write_numbers_as_strings: true
  redis:
    host: 127.0.0.1
    port: 6379
springfox:
  documentation:
    swagger-ui:
      enabled: true
test:
  hello: ziuch
